-- AUTO-GENERATED by scripts/generate-seed.js
-- Run AFTER 001_products_schema.sql in Supabase SQL Editor

insert into brands (name, slug) values
  ('Keychron', 'keychron'),
  ('Akko', 'akko'),
  ('Epomaker', 'epomaker'),
  ('Varmilo', 'varmilo'),
  ('Monsgeek', 'monsgeek'),
  ('GuliKit', 'gulikit'),
  ('Hori', 'hori')
on conflict (slug) do nothing;

-- TASTATURI (60 products)
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Tastatura wireless Keychron B6 Pro, Ultra-Slim, US layout, 2.4GHz/Bluetooth, autonomie baterie 1200h, telefon/tableta/PC/Mac', 'tastatura-wireless-keychron-b6-pro-ultra-slim-us-layout-2-4ghz-bluetooth-autonomie-baterie-1200h-telefon-tableta-pc-mac', 'Tastatura wireless Keychron B6 Pro, Ultra-Slim, US layout, 2.4GHz/Bluetooth, autonomie baterie 1200h, telefon/tableta/PC/Mac', 0, '{"switch_type":"Scissor","hot_swap":false,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Tastatura mecanica wireless Keychron J4, BT/2.4GHz/Wired, switch-uri Red Super, RGB LED, QMK, macOS/Windows/Linux', 'tastatura-mecanica-wireless-keychron-j4-bt-2-4ghz-wired-switch-uri-red-super-rgb-led-qmk-macos-windows-linux', 'Tastatura mecanica wireless Keychron J4, BT/2.4GHz/Wired, switch-uri Red Super, RGB LED, QMK, macOS/Windows/Linux', 0, '{"switch_type":"Keychron Super Red","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Tastatura mecanica wired Keychron V1 8K, switch-uri mecanice red, cablu type-A to type-C, negru, layout 82 Key Black, macOS/Windows/Linux', 'tastatura-mecanica-wired-keychron-v1-8k-switch-uri-mecanice-red-cablu-type-a-to-type-c-negru-layout-82-key-black-macos-windows-linux', 'Tastatura mecanica wired Keychron V1 8K, switch-uri mecanice red, cablu type-A to type-C, negru, layout 82 Key Black, macOS/Windows/Linux', 0, '{"switch_type":"Keychron K Pro Red","hot_swap":true,"polling_rate_8k":true,"connectivity":["USB-C"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Tastatura mecanica wireless Keychron K5 Max Low Profile K5M-H1, iluminare RGB, negru/gri', 'tastatura-mecanica-wireless-keychron-k5-max-low-profile-k5m-h1-iluminare-rgb-negru-gri', 'Tastatura mecanica wireless Keychron K5 Max Low Profile K5M-H1, iluminare RGB, negru/gri', 0, '{"switch_type":"Gateron Low-Profile Mechanical","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Tastatura mecanica wireless Keychron V6 Ultra 8K, BT/2.4GHz/Wired, switch-uri Brown Silk POM, RGB LED, QMK, macOS/Windows/Linux', 'tastatura-mecanica-wireless-keychron-v6-ultra-8k-bt-2-4ghz-wired-switch-uri-brown-silk-pom-rgb-led-qmk-macos-windows-linux', 'Tastatura mecanica wireless Keychron V6 Ultra 8K, BT/2.4GHz/Wired, switch-uri Brown Silk POM, RGB LED, QMK, macOS/Windows/Linux', 0, '{"switch_type":"Brown Silk POM","hot_swap":true,"polling_rate_8k":true,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Tastatura mecanica wired gaming Keychron J2 HE 8K, USB-C, comutatoare Hall/TMR, layout compact, QMK Launcher, macOS/Windows/Linux', 'tastatura-mecanica-wired-gaming-keychron-j2-he-8k-usb-c-comutatoare-hall-tmr-layout-compact-qmk-launcher-macos-windows-linux', 'Tastatura mecanica wired gaming Keychron J2 HE 8K, USB-C, comutatoare Hall/TMR, layout compact, QMK Launcher, macOS/Windows/Linux', 0, '{"switch_type":"TMR","hot_swap":true,"polling_rate_8k":true,"connectivity":["USB-C"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Tastatura mecanica wired Keychron V1 8K, switch-uri mecanice brown, cablu type-A to type-C, negru, layout 82 Key Black, macOS/Windows/Linux', 'tastatura-mecanica-wired-keychron-v1-8k-switch-uri-mecanice-brown-cablu-type-a-to-type-c-negru-layout-82-key-black-macos-windows-linux', 'Tastatura mecanica wired Keychron V1 8K, switch-uri mecanice brown, cablu type-A to type-C, negru, layout 82 Key Black, macOS/Windows/Linux', 0, '{"switch_type":"Keychron K Pro Brown","hot_swap":true,"polling_rate_8k":true,"connectivity":["USB-C"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Tastatura mecanica wireless Keychron Q6 HE 8K, 2.4GHz/Bluetooth, switch-uri Ultra-Fast Lime Magnetic, iluminare RGB LED, macOS/Windows/Linux', 'tastatura-mecanica-wireless-keychron-q6-he-8k-2-4ghz-bluetooth-switch-uri-ultra-fast-lime-magnetic-iluminare-rgb-led-macos-windows-linux', 'Tastatura mecanica wireless Keychron Q6 HE 8K, 2.4GHz/Bluetooth, switch-uri Ultra-Fast Lime Magnetic, iluminare RGB LED, macOS/Windows/Linux', 0, '{"switch_type":"Ultra-Fast Lime Magnetic","hot_swap":true,"polling_rate_8k":true,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Tastatura mecanica wireless Keychron V3 Ultra 8K, BT/2.4GHz/Wired, switch-uri Brown Silk POM, RGB LED, QMK, macOS/Windows/Linux', 'tastatura-mecanica-wireless-keychron-v3-ultra-8k-bt-2-4ghz-wired-switch-uri-brown-silk-pom-rgb-led-qmk-macos-windows-linux', 'Tastatura mecanica wireless Keychron V3 Ultra 8K, BT/2.4GHz/Wired, switch-uri Brown Silk POM, RGB LED, QMK, macOS/Windows/Linux', 0, '{"switch_type":"Brown Silk POM","hot_swap":true,"polling_rate_8k":true,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Tastatura mecanica wired Keychron C4 HE, switch-uri Ultra-Fast Lime Magnetic, cablu USB-C, negru, Full Size 104 Key, macOS/Windows/Linux', 'tastatura-mecanica-wired-keychron-c4-he-switch-uri-ultra-fast-lime-magnetic-cablu-usb-c-negru-full-size-104-key-macos-windows-linux', 'Tastatura mecanica wired Keychron C4 HE, switch-uri Ultra-Fast Lime Magnetic, cablu USB-C, negru, Full Size 104 Key, macOS/Windows/Linux', 0, '{"switch_type":"Ultra-Fast Lime Magnetic","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Tastatura mecanica Akko MOD 007HE PC Purple Melody, USB, iluminare RGB', 'tastatura-mecanica-akko-mod-007he-pc-purple-melody-usb-iluminare-rgb', 'Tastatura mecanica Akko MOD 007HE PC Purple Melody, USB, iluminare RGB', 0, '{"switch_type":"Akko Cream Yellow Magnetic","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C"]}'::jsonb
from brands b, categories c
where b.slug = 'akko' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Tastatura mecanica wireless Akko 5098B Plus Prunus Lannesiana, iluminare RGB, roz/alb', 'tastatura-mecanica-wireless-akko-5098b-plus-prunus-lannesiana-iluminare-rgb-roz-alb', 'Tastatura mecanica wireless Akko 5098B Plus Prunus Lannesiana, iluminare RGB, roz/alb', 0, '{"switch_type":"Akko V3 Piano Pro","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'akko' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Tastatura mecanica wireless Akko JIN01 Santorini, carcasa aluminiu, iluminare RGB, alb/albastru', 'tastatura-mecanica-wireless-akko-jin01-santorini-carcasa-aluminiu-iluminare-rgb-alb-albastru', 'Tastatura mecanica wireless Akko JIN01 Santorini, carcasa aluminiu, iluminare RGB, alb/albastru', 0, '{"switch_type":"Akko Rosewood","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'akko' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Tastatura mecanica wireless Akko MU02 Mountain Seclusion, iluminare RGB, lemn', 'tastatura-mecanica-wireless-akko-mu02-mountain-seclusion-iluminare-rgb-lemn', 'Tastatura mecanica wireless Akko MU02 Mountain Seclusion, iluminare RGB, lemn', 0, '{"switch_type":"Akko Rosewood","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'akko' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Tastatura mecanica wireless Akko TAC87 Bun Wonderland, iluminare RGB', 'tastatura-mecanica-wireless-akko-tac87-bun-wonderland-iluminare-rgb', 'Tastatura mecanica wireless Akko TAC87 Bun Wonderland, iluminare RGB', 0, '{"switch_type":"Akko Stellar Rose","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'akko' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Tastatura mecanica wireless Akko X The King’s Avatar 5098B Ye Xiu, iluminare RGB', 'tastatura-mecanica-wireless-akko-x-the-king-s-avatar-5098b-ye-xiu-iluminare-rgb', 'Tastatura mecanica wireless Akko X The King’s Avatar 5098B Ye Xiu, iluminare RGB', 0, '{"switch_type":"Akko V3 Piano Pro","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'akko' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Tastatura gaming mecanica wireless Epomaker G84 Pink, iluminare RGB', 'tastatura-gaming-mecanica-wireless-epomaker-g84-pink-iluminare-rgb', 'Tastatura gaming mecanica wireless Epomaker G84 Pink, iluminare RGB', 0, '{"switch_type":"Epomaker Creamy Jade","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'epomaker' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Tastatura gaming mecanica wireless Epomaker Galaxy 100 Grey, iluminare RGB', 'tastatura-gaming-mecanica-wireless-epomaker-galaxy-100-grey-iluminare-rgb', 'Tastatura gaming mecanica wireless Epomaker Galaxy 100 Grey, iluminare RGB', 0, '{"switch_type":"Feker Marble White","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'epomaker' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Tastatura gaming mecanica wireless Epomaker HE75 Mag, iluminare RGB', 'tastatura-gaming-mecanica-wireless-epomaker-he75-mag-iluminare-rgb', 'Tastatura gaming mecanica wireless Epomaker HE75 Mag, iluminare RGB', 0, '{"switch_type":"Gateron Magnetic White","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'epomaker' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Tastatura mecanica wireless Keychron V3 Ultra 8K, BT/2.4GHz/Wired, switch-uri Brown Silk POM, RGB LED, QMK, macOS/Windows/Linux', 'tastatura-mecanica-wireless-keychron-v3-ultra-8k-bt-2-4ghz-wired-switch-uri-brown-silk-pom-rgb-led-qmk-macos-windows-linux', 'Tastatura mecanica wireless Keychron V3 Ultra 8K, BT/2.4GHz/Wired, switch-uri Brown Silk POM, RGB LED, QMK, macOS/Windows/Linux', 0, '{"switch_type":"Brown Silk POM","hot_swap":true,"polling_rate_8k":true,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Tastatura mecanica wireless Keychron V6 Ultra 8K, BT/2.4GHz/Wired, switch-uri Red Silk POM, RGB LED, QMK, macOS/Windows/Linux', 'tastatura-mecanica-wireless-keychron-v6-ultra-8k-bt-2-4ghz-wired-switch-uri-red-silk-pom-rgb-led-qmk-macos-windows-linux', 'Tastatura mecanica wireless Keychron V6 Ultra 8K, BT/2.4GHz/Wired, switch-uri Red Silk POM, RGB LED, QMK, macOS/Windows/Linux', 0, '{"switch_type":"Red Silk POM","hot_swap":true,"polling_rate_8k":true,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Tastatura mecanica wireless Keychron K17 Max Low Profile K17M-H1, iluminare RGB, negru/gri', 'tastatura-mecanica-wireless-keychron-k17-max-low-profile-k17m-h1-iluminare-rgb-negru-gri', 'Tastatura mecanica wireless Keychron K17 Max Low Profile K17M-H1, iluminare RGB, negru/gri', 0, '{"switch_type":"Gateron Low-Profile Mechanical","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Tastatura wireless Keychron B36-K9, negru', 'tastatura-wireless-keychron-b36-k9-negru', 'Tastatura wireless Keychron B36-K9, negru', 0, '{"switch_type":"Scissor","hot_swap":false,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Tastatura mecanica Varmilo Muse65 Aurora, Blue', 'tastatura-mecanica-varmilo-muse65-aurora-blue', 'Tastatura mecanica Varmilo Muse65 Aurora, Blue', 0, '{"switch_type":"Gateron KS-20 White Magnetic","hot_swap":true,"polling_rate_8k":true,"connectivity":["USB-C"]}'::jsonb
from brands b, categories c
where b.slug = 'varmilo' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Tastatura mecanica wireless Varmilo Minilo75 Pro Bluebell, iluminare RGB', 'tastatura-mecanica-wireless-varmilo-minilo75-pro-bluebell-iluminare-rgb', 'Tastatura mecanica wireless Varmilo Minilo75 Pro Bluebell, iluminare RGB', 0, '{"switch_type":"Kailh Prestige Silent","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'varmilo' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Tastatura mecanica wireless Varmilo Minilo75 Pro Retro, iluminare RGB', 'tastatura-mecanica-wireless-varmilo-minilo75-pro-retro-iluminare-rgb', 'Tastatura mecanica wireless Varmilo Minilo75 Pro Retro, iluminare RGB', 0, '{"switch_type":"Kailh Prestige Silent","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'varmilo' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Tastatura mecanica wireless Varmilo VA100, iluminare RGB', 'tastatura-mecanica-wireless-varmilo-va100-iluminare-rgb', 'Tastatura mecanica wireless Varmilo VA100, iluminare RGB', 0, '{"switch_type":"Kailh Prestige","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'varmilo' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Tastatura gaming mecanica wireless Epomaker Galaxy 100 Black, iluminare RGB', 'tastatura-gaming-mecanica-wireless-epomaker-galaxy-100-black-iluminare-rgb', 'Tastatura gaming mecanica wireless Epomaker Galaxy 100 Black, iluminare RGB', 0, '{"switch_type":"Feker Marble White","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'epomaker' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'TASTATURA GAMING WIRELESS MECANICA KEYCHRON K10 HE STANDARD EDITION, BLUETOOTH, USB, LAYOUT US, NEGRU', 'tastatura-gaming-wireless-mecanica-keychron-k10-he-standard-edition-bluetooth-usb-layout-us-negru', 'TASTATURA GAMING WIRELESS MECANICA KEYCHRON K10 HE STANDARD EDITION, BLUETOOTH, USB, LAYOUT US, NEGRU', 0, '{"switch_type":"Gateron Double-Rail Magnetic","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'TASTATURA GAMING WIRELESS MECANICA KEYCHRON K10 HE, BLUETOOTH, USB, LAYOUT US, NEGRU', 'tastatura-gaming-wireless-mecanica-keychron-k10-he-bluetooth-usb-layout-us-negru', 'TASTATURA GAMING WIRELESS MECANICA KEYCHRON K10 HE, BLUETOOTH, USB, LAYOUT US, NEGRU', 0, '{"switch_type":"Gateron Double-Rail Magnetic","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'TASTATURA GAMING WIRELESS MAGNETICA KEYCHRON K2 HE K2H-J1, BLUETOOTH, USB, LAYOUT US, NEGRU', 'tastatura-gaming-wireless-magnetica-keychron-k2-he-k2h-j1-bluetooth-usb-layout-us-negru', 'TASTATURA GAMING WIRELESS MAGNETICA KEYCHRON K2 HE K2H-J1, BLUETOOTH, USB, LAYOUT US, NEGRU', 0, '{"switch_type":"Gateron Double-Rail Magnetic","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'TASTATURA GAMING WIRELESS MAGNETICA KEYCHRON K2 HE K2H-F1, BLUETOOTH, USB, LAYOUT US, NEGRU', 'tastatura-gaming-wireless-magnetica-keychron-k2-he-k2h-f1-bluetooth-usb-layout-us-negru', 'TASTATURA GAMING WIRELESS MAGNETICA KEYCHRON K2 HE K2H-F1, BLUETOOTH, USB, LAYOUT US, NEGRU', 0, '{"switch_type":"Gateron Double-Rail Magnetic","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'TASTATURA GAMING WIRELESS KEYCHRON B1 PRO ULTRA-SLIM, BLUETOOTH, USB, LAYOUT US, ALB', 'tastatura-gaming-wireless-keychron-b1-pro-ultra-slim-bluetooth-usb-layout-us-alb', 'TASTATURA GAMING WIRELESS KEYCHRON B1 PRO ULTRA-SLIM, BLUETOOTH, USB, LAYOUT US, ALB', 0, '{"switch_type":"Scissor","hot_swap":false,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'TASTATURA GAMING MECANICA KEYCHRON C3 PRO RED SWITCH, USB, LAYOUT US, NEGRU', 'tastatura-gaming-mecanica-keychron-c3-pro-red-switch-usb-layout-us-negru', 'TASTATURA GAMING MECANICA KEYCHRON C3 PRO RED SWITCH, USB, LAYOUT US, NEGRU', 0, '{"switch_type":"Keychron K Pro Red","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'TASTATURA GAMING WIRELESS KEYCHRON B6 PRO ULTRA-SLIM, BLUETOOTH, USB, LAYOUT US, GRI', 'tastatura-gaming-wireless-keychron-b6-pro-ultra-slim-bluetooth-usb-layout-us-gri', 'TASTATURA GAMING WIRELESS KEYCHRON B6 PRO ULTRA-SLIM, BLUETOOTH, USB, LAYOUT US, GRI', 0, '{"switch_type":"Scissor","hot_swap":false,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'TASTATURA GAMING WIRELESS MECANICA KEYCHRON K10 MAX QMK FULL, BLUETOOTH, USB, NEGRU', 'tastatura-gaming-wireless-mecanica-keychron-k10-max-qmk-full-bluetooth-usb-negru', 'TASTATURA GAMING WIRELESS MECANICA KEYCHRON K10 MAX QMK FULL, BLUETOOTH, USB, NEGRU', 0, '{"switch_type":"Keychron Super Brown","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'TASTATURA GAMING WIRELESS MAGNETICA KEYCHRON K4 HE STANDARD EDITION, BLUETOOTH, USB, LAYOUT USB, NEGRU', 'tastatura-gaming-wireless-magnetica-keychron-k4-he-standard-edition-bluetooth-usb-layout-usb-negru', 'TASTATURA GAMING WIRELESS MAGNETICA KEYCHRON K4 HE STANDARD EDITION, BLUETOOTH, USB, LAYOUT USB, NEGRU', 0, '{"switch_type":"Gateron Double-Rail Magnetic","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'TASTATURA GAMING WIRELESS MAGNETICA KEYCHRON K4 HE SPECIAL EDITION, BLUETOOTH, USB, LAYOUT USB, NEGRU', 'tastatura-gaming-wireless-magnetica-keychron-k4-he-special-edition-bluetooth-usb-layout-usb-negru', 'TASTATURA GAMING WIRELESS MAGNETICA KEYCHRON K4 HE SPECIAL EDITION, BLUETOOTH, USB, LAYOUT USB, NEGRU', 0, '{"switch_type":"Gateron Double-Rail Magnetic","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'TASTATURA GAMING MECANICA KEYCHRON C3 PRO BROWN SWITCH, USB, LAYOUT US, NEGRU', 'tastatura-gaming-mecanica-keychron-c3-pro-brown-switch-usb-layout-us-negru', 'TASTATURA GAMING MECANICA KEYCHRON C3 PRO BROWN SWITCH, USB, LAYOUT US, NEGRU', 0, '{"switch_type":"Keychron K Pro Brown","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'TASTATURA GAMING WIRELESS KEYCHRON B1 PRO ULTRA-SLIM, BLUETOOTH, USB, LAYOUT US, GRI', 'tastatura-gaming-wireless-keychron-b1-pro-ultra-slim-bluetooth-usb-layout-us-gri', 'TASTATURA GAMING WIRELESS KEYCHRON B1 PRO ULTRA-SLIM, BLUETOOTH, USB, LAYOUT US, GRI', 0, '{"switch_type":"Scissor","hot_swap":false,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'TASTATURA GAMING WIRELESS MECANICA AKKO HATSUNE MIKU 5108B PLUS, BLUETOOTH, USB, LAYOUT US, VERDE', 'tastatura-gaming-wireless-mecanica-akko-hatsune-miku-5108b-plus-bluetooth-usb-layout-us-verde', 'TASTATURA GAMING WIRELESS MECANICA AKKO HATSUNE MIKU 5108B PLUS, BLUETOOTH, USB, LAYOUT US, VERDE', 0, '{"switch_type":"Akko V3 Creamy Blue Pro","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'akko' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'TASTATURA GAMING MECANICA VARMILO MUSE65, USB, LAYOUT US, NEGRU', 'tastatura-gaming-mecanica-varmilo-muse65-usb-layout-us-negru', 'TASTATURA GAMING MECANICA VARMILO MUSE65, USB, LAYOUT US, NEGRU', 0, '{"switch_type":"Gateron KS-20 White Magnetic","hot_swap":true,"polling_rate_8k":true,"connectivity":["USB-C"]}'::jsonb
from brands b, categories c
where b.slug = 'varmilo' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'TASTATURA GAMING WIRELESS MECANICA VARMILO VA80 HYGGE, BLUETOOTH, USB, LAYOUT US, NEGRU', 'tastatura-gaming-wireless-mecanica-varmilo-va80-hygge-bluetooth-usb-layout-us-negru', 'TASTATURA GAMING WIRELESS MECANICA VARMILO VA80 HYGGE, BLUETOOTH, USB, LAYOUT US, NEGRU', 0, '{"switch_type":"Kailh Prestige","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'varmilo' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'TASTATURA GAMING WIRELESS MECANICA MONSGEEK M1 V5 CONTOUR LINES, BLUETOOTH, USB, LAYOUT US, NEGRU', 'tastatura-gaming-wireless-mecanica-monsgeek-m1-v5-contour-lines-bluetooth-usb-layout-us-negru', 'TASTATURA GAMING WIRELESS MECANICA MONSGEEK M1 V5 CONTOUR LINES, BLUETOOTH, USB, LAYOUT US, NEGRU', 0, '{"switch_type":"Akko V3 Creamy Yellow Pro","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'monsgeek' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'TASTATURA GAMING WIRELESS MECANICA EPOMAKER G84, BLUETOOTH, USB, LAYOUT US, NEGRU', 'tastatura-gaming-wireless-mecanica-epomaker-g84-bluetooth-usb-layout-us-negru', 'TASTATURA GAMING WIRELESS MECANICA EPOMAKER G84, BLUETOOTH, USB, LAYOUT US, NEGRU', 0, '{"switch_type":"Epomaker Creamy Jade","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'epomaker' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'TASTATURA GAMING MECANICA AKKO MOD007 HE YEAR OF DRAGON, USB, LAYOUT US, VERDE', 'tastatura-gaming-mecanica-akko-mod007-he-year-of-dragon-usb-layout-us-verde', 'TASTATURA GAMING MECANICA AKKO MOD007 HE YEAR OF DRAGON, USB, LAYOUT US, VERDE', 0, '{"switch_type":"Akko Cream Yellow Magnetic","hot_swap":true,"polling_rate_8k":true,"connectivity":["USB-C"]}'::jsonb
from brands b, categories c
where b.slug = 'akko' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'TASTATURA GAMING WIRELESS MECANICA AKKO DRACULA CASTLE 5075B PLUS, BLUETOOTH, USB, LAYOUT US, NEGRU', 'tastatura-gaming-wireless-mecanica-akko-dracula-castle-5075b-plus-bluetooth-usb-layout-us-negru', 'TASTATURA GAMING WIRELESS MECANICA AKKO DRACULA CASTLE 5075B PLUS, BLUETOOTH, USB, LAYOUT US, NEGRU', 0, '{"switch_type":"Akko V3 Creamy Blue Pro","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'akko' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'TASTATURA GAMING WIRELESS MECANICA AKKO INK GREEN 5098B, BLUETOOTH, USB, LAYOUT US, VERDE', 'tastatura-gaming-wireless-mecanica-akko-ink-green-5098b-bluetooth-usb-layout-us-verde', 'TASTATURA GAMING WIRELESS MECANICA AKKO INK GREEN 5098B, BLUETOOTH, USB, LAYOUT US, VERDE', 0, '{"switch_type":"Akko V3 Piano Pro","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'akko' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'TASTATURA GAMING WIRELESS MECANICA EPOMAKER TH108, BLUETOOTH, USB, LAYOUT US, NEGRU', 'tastatura-gaming-wireless-mecanica-epomaker-th108-bluetooth-usb-layout-us-negru', 'TASTATURA GAMING WIRELESS MECANICA EPOMAKER TH108, BLUETOOTH, USB, LAYOUT US, NEGRU', 0, '{"switch_type":"Epomaker Creamy Jade","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'epomaker' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'TASTATURA GAMING WIRELESS MECANICA AKKO MU01 MOUNTAIN SECLUSION, BLUETOOTH, USB, LAYOUT US, MARO', 'tastatura-gaming-wireless-mecanica-akko-mu01-mountain-seclusion-bluetooth-usb-layout-us-maro', 'TASTATURA GAMING WIRELESS MECANICA AKKO MU01 MOUNTAIN SECLUSION, BLUETOOTH, USB, LAYOUT US, MARO', 0, '{"switch_type":"Akko Rosewood","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'akko' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'TASTATURA GAMING MECANICA EPOMAKER HE68 LITE, USB, LAYOUT US, NEGRU', 'tastatura-gaming-mecanica-epomaker-he68-lite-usb-layout-us-negru', 'TASTATURA GAMING MECANICA EPOMAKER HE68 LITE, USB, LAYOUT US, NEGRU', 0, '{"switch_type":"Epomaker Clear Mag Switch","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C"]}'::jsonb
from brands b, categories c
where b.slug = 'epomaker' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'TASTATURA GAMING WIRELESS MAGNETICA KEYCHRON K8 HE SPECIAL EDITION, BLUETOOTH, USB, LAYOUT US, NEGRU', 'tastatura-gaming-wireless-magnetica-keychron-k8-he-special-edition-bluetooth-usb-layout-us-negru', 'TASTATURA GAMING WIRELESS MAGNETICA KEYCHRON K8 HE SPECIAL EDITION, BLUETOOTH, USB, LAYOUT US, NEGRU', 0, '{"switch_type":"Gateron Double-Rail Magnetic","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'TASTATURA GAMING WIRELESS MECANICA AKKO WASTELAND SURVIVAL 5098B, BLUETOOTH, USB, LAYOUT US, NEGRU-MARO', 'tastatura-gaming-wireless-mecanica-akko-wasteland-survival-5098b-bluetooth-usb-layout-us-negru-maro', 'TASTATURA GAMING WIRELESS MECANICA AKKO WASTELAND SURVIVAL 5098B, BLUETOOTH, USB, LAYOUT US, NEGRU-MARO', 0, '{"switch_type":"Akko V3 Piano Pro","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'akko' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'TASTATURA GAMING MECANICA EPOMAKER HE80, USB, LAYOUT US, NEGRU', 'tastatura-gaming-mecanica-epomaker-he80-usb-layout-us-negru', 'TASTATURA GAMING MECANICA EPOMAKER HE80, USB, LAYOUT US, NEGRU', 0, '{"switch_type":"Epomaker MagneX Switch","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C"]}'::jsonb
from brands b, categories c
where b.slug = 'epomaker' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'TASTATURA GAMING WIRELESS MECANICA MONSGEEK FUN60 ULTRA ST, BLUETOOTH, USB, LAYOUT US, NEGRU', 'tastatura-gaming-wireless-mecanica-monsgeek-fun60-ultra-st-bluetooth-usb-layout-us-negru', 'TASTATURA GAMING WIRELESS MECANICA MONSGEEK FUN60 ULTRA ST, BLUETOOTH, USB, LAYOUT US, NEGRU', 0, '{"switch_type":"Glare Magnetic TMR","hot_swap":true,"polling_rate_8k":true,"connectivity":["USB-C"]}'::jsonb
from brands b, categories c
where b.slug = 'monsgeek' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'TASTATURA GAMING WIRELESS MAGNETICA KEYCHRON K8 HE STANDARD EDITION, BLUETOOTH, USB, LAYOUT US, NEGRU', 'tastatura-gaming-wireless-magnetica-keychron-k8-he-standard-edition-bluetooth-usb-layout-us-negru', 'TASTATURA GAMING WIRELESS MAGNETICA KEYCHRON K8 HE STANDARD EDITION, BLUETOOTH, USB, LAYOUT US, NEGRU', 0, '{"switch_type":"Gateron Double-Rail Magnetic","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'TASTATURA GAMING WIRELESS KEYCHRON B6 PRO ULTRA-SLIM, BLUETOOTH, USB, LAYOUT US, ALB', 'tastatura-gaming-wireless-keychron-b6-pro-ultra-slim-bluetooth-usb-layout-us-alb', 'TASTATURA GAMING WIRELESS KEYCHRON B6 PRO ULTRA-SLIM, BLUETOOTH, USB, LAYOUT US, ALB', 0, '{"switch_type":"Scissor","hot_swap":false,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'TASTATURA GAMING WIRELESS MECANICA KEYCHRON K10 QMK VERSION 2, BLUETOOTH, USB, BROWN SWITCH, LAYOUT US, NEGRU', 'tastatura-gaming-wireless-mecanica-keychron-k10-qmk-version-2-bluetooth-usb-brown-switch-layout-us-negru', 'TASTATURA GAMING WIRELESS MECANICA KEYCHRON K10 QMK VERSION 2, BLUETOOTH, USB, BROWN SWITCH, LAYOUT US, NEGRU', 0, '{"switch_type":"Keychron Super Brown","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'TASTATURA GAMING WIRELESS MECANICA KEYCHRON K8 QMK VERSION 2, BLUETOOTH, USB, BROWN SWITCH, LAYOUT US, NEGRU', 'tastatura-gaming-wireless-mecanica-keychron-k8-qmk-version-2-bluetooth-usb-brown-switch-layout-us-negru', 'TASTATURA GAMING WIRELESS MECANICA KEYCHRON K8 QMK VERSION 2, BLUETOOTH, USB, BROWN SWITCH, LAYOUT US, NEGRU', 0, '{"switch_type":"Keychron Super Brown","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'tastaturi'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'TASTATURA GAMING WIRELESS MECANICA KEYCHRON K8 MAX QMK, BLUETOOTH, USB, LAYOUT US, NEGRU', 'tastatura-gaming-wireless-mecanica-keychron-k8-max-qmk-bluetooth-usb-layout-us-negru', 'TASTATURA GAMING WIRELESS MECANICA KEYCHRON K8 MAX QMK, BLUETOOTH, USB, LAYOUT US, NEGRU', 0, '{"switch_type":"Keychron Super Brown","hot_swap":true,"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'tastaturi'
on conflict (slug) do nothing;

-- MOUSE-URI (10 products)
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Mouse business Keychron BM24, 2.4GHz Bluetooth USB-C, senzor PAW3212, autonomie 100-120h, compatibil Windows macOS', 'mouse-business-keychron-bm24-2-4ghz-bluetooth-usb-c-senzor-paw3212-autonomie-100-120h-compatibil-windows-macos', 'Mouse business Keychron BM24, 2.4GHz Bluetooth USB-C, senzor PAW3212, autonomie 100-120h, compatibil Windows macOS', 0, '{"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'mouse-uri'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Mouse wireless Keychron M6 8K, 2.4GHz Bluetooth USB-C, PixArt 30000 DPI, polling 1K-8K Hz, rotita thumb wheel, compatibil Windows macOS', 'mouse-wireless-keychron-m6-8k-2-4ghz-bluetooth-usb-c-pixart-30000-dpi-polling-1k-8k-hz-rotita-thumb-wheel-compatibil-windows-macos', 'Mouse wireless Keychron M6 8K, 2.4GHz Bluetooth USB-C, PixArt 30000 DPI, polling 1K-8K Hz, rotita thumb wheel, compatibil Windows macOS', 0, '{"polling_rate_8k":true,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'mouse-uri'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Mouse wireless Keychron M6, 2.4GHz Bluetooth USB-C, PixArt 30000 DPI, rotita duala, compatibil Windows macOS', 'mouse-wireless-keychron-m6-2-4ghz-bluetooth-usb-c-pixart-30000-dpi-rotita-duala-compatibil-windows-macos', 'Mouse wireless Keychron M6, 2.4GHz Bluetooth USB-C, PixArt 30000 DPI, rotita duala, compatibil Windows macOS', 0, '{"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'mouse-uri'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Mouse wireless Akko Cat Theme, 1200 DPI, Orange', 'mouse-wireless-akko-cat-theme-1200-dpi-orange', 'Mouse wireless Akko Cat Theme, 1200 DPI, Orange', 0, '{"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'akko' and c.slug = 'mouse-uri'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'MOUSE GAMING WIRELESS KEYCHRON M7, 26000 DPI, NEGRU', 'mouse-gaming-wireless-keychron-m7-26000-dpi-negru', 'MOUSE GAMING WIRELESS KEYCHRON M7, 26000 DPI, NEGRU', 0, '{"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'mouse-uri'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'MOUSE GAMING WIRELESS KEYCHRON M3, 26000 DPI, NEGRU', 'mouse-gaming-wireless-keychron-m3-26000-dpi-negru', 'MOUSE GAMING WIRELESS KEYCHRON M3, 26000 DPI, NEGRU', 0, '{"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'mouse-uri'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'MOUSE GAMING WIRELESS KEYCHRON M6, 26000 DPI, NEGRU', 'mouse-gaming-wireless-keychron-m6-26000-dpi-negru', 'MOUSE GAMING WIRELESS KEYCHRON M6, 26000 DPI, NEGRU', 0, '{"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'keychron' and c.slug = 'mouse-uri'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'MOUSE GAMING WIRELESS AKKO AG ONE LORD OF MYSTERIES, 26000 DPI, NEGRU', 'mouse-gaming-wireless-akko-ag-one-lord-of-mysteries-26000-dpi-negru', 'MOUSE GAMING WIRELESS AKKO AG ONE LORD OF MYSTERIES, 26000 DPI, NEGRU', 0, '{"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'akko' and c.slug = 'mouse-uri'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'MOUSE GAMING WIRELESS EPOMAKER CARBON X, 42000 DPI, NEGRU', 'mouse-gaming-wireless-epomaker-carbon-x-42000-dpi-negru', 'MOUSE GAMING WIRELESS EPOMAKER CARBON X, 42000 DPI, NEGRU', 0, '{"polling_rate_8k":true,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'epomaker' and c.slug = 'mouse-uri'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'MOUSE GAMING WIRELESS EPOMAKER CLICK LITE, 24000 DPI, NEGRU', 'mouse-gaming-wireless-epomaker-click-lite-24000-dpi-negru', 'MOUSE GAMING WIRELESS EPOMAKER CLICK LITE, 24000 DPI, NEGRU', 0, '{"polling_rate_8k":false,"connectivity":["USB-C","Bluetooth","2.4 GHz Wireless"]}'::jsonb
from brands b, categories c
where b.slug = 'epomaker' and c.slug = 'mouse-uri'
on conflict (slug) do nothing;

-- CONTROLLERE (17 products)
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'CONTROLLER WIRELESS GULIKIT KK2T, PC/NINTENDO SWITCH, NEGRU', 'controller-wireless-gulikit-kk2t-pc-nintendo-switch-negru', 'CONTROLLER WIRELESS GULIKIT KK2T, PC/NINTENDO SWITCH, NEGRU', 0, '{}'::jsonb
from brands b, categories c
where b.slug = 'gulikit' and c.slug = 'controllere'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'CONTROLLER WIRELESS GULIKIT KK3 MAX, PC/NINTENDO SWITCH, NEGRU', 'controller-wireless-gulikit-kk3-max-pc-nintendo-switch-negru', 'CONTROLLER WIRELESS GULIKIT KK3 MAX, PC/NINTENDO SWITCH, NEGRU', 0, '{}'::jsonb
from brands b, categories c
where b.slug = 'gulikit' and c.slug = 'controllere'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'CONTROLLER WIRELESS GULIKIT KK3 PRO, PS/NINTENDO SWITCH, NEGRU', 'controller-wireless-gulikit-kk3-pro-ps-nintendo-switch-negru', 'CONTROLLER WIRELESS GULIKIT KK3 PRO, PS/NINTENDO SWITCH, NEGRU', 0, '{}'::jsonb
from brands b, categories c
where b.slug = 'gulikit' and c.slug = 'controllere'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'CONTROLLER WIRELESS GULIKIT KK3 MAX, PC/NINTENDO SWITCH, GRI', 'controller-wireless-gulikit-kk3-max-pc-nintendo-switch-gri', 'CONTROLLER WIRELESS GULIKIT KK3 MAX, PC/NINTENDO SWITCH, GRI', 0, '{}'::jsonb
from brands b, categories c
where b.slug = 'gulikit' and c.slug = 'controllere'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'CONTROLLER WIRELESS GULIKIT KK3 PRO, PS/NINTENDO SWITCH, GREY', 'controller-wireless-gulikit-kk3-pro-ps-nintendo-switch-grey', 'CONTROLLER WIRELESS GULIKIT KK3 PRO, PS/NINTENDO SWITCH, GREY', 0, '{}'::jsonb
from brands b, categories c
where b.slug = 'gulikit' and c.slug = 'controllere'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'CONTROLLER WIRELESS HORI FIGHTING COMMANDER OCTA PRO, PS5/PC, NEGRU', 'controller-wireless-hori-fighting-commander-octa-pro-ps5-pc-negru', 'CONTROLLER WIRELESS HORI FIGHTING COMMANDER OCTA PRO, PS5/PC, NEGRU', 0, '{}'::jsonb
from brands b, categories c
where b.slug = 'hori' and c.slug = 'controllere'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Controller HORI D-Pad Controller (L) Pokemon: Pikachu Black & Gold Edition', 'controller-hori-d-pad-controller-l-pokemon-pikachu-black-gold-edition', 'Controller HORI D-Pad Controller (L) Pokemon: Pikachu Black & Gold Edition', 0, '{}'::jsonb
from brands b, categories c
where b.slug = 'hori' and c.slug = 'controllere'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'HORI WIRELESS HORIPAD (BLUE) PENTRU NINTENDO SWITCH, SWITCH OLED SI SWITCH LITE', 'hori-wireless-horipad-blue-pentru-nintendo-switch-switch-oled-si-switch-lite', 'HORI WIRELESS HORIPAD (BLUE) PENTRU NINTENDO SWITCH, SWITCH OLED SI SWITCH LITE', 0, '{}'::jsonb
from brands b, categories c
where b.slug = 'hori' and c.slug = 'controllere'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'HORI D-PAD CONTROLLER (SUPER MARIO - NEW DESIGN) PENTRU NINTENDO SWITCH SI SWITCH OLED', 'hori-d-pad-controller-super-mario-new-design-pentru-nintendo-switch-si-switch-oled', 'HORI D-PAD CONTROLLER (SUPER MARIO - NEW DESIGN) PENTRU NINTENDO SWITCH SI SWITCH OLED', 0, '{}'::jsonb
from brands b, categories c
where b.slug = 'hori' and c.slug = 'controllere'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'HORI FIGHTING COMMANDER OCTA PENTRU XBOX SERIES X/S, XBOX ONE SI PC', 'hori-fighting-commander-octa-pentru-xbox-series-x-s-xbox-one-si-pc', 'HORI FIGHTING COMMANDER OCTA PENTRU XBOX SERIES X/S, XBOX ONE SI PC', 0, '{}'::jsonb
from brands b, categories c
where b.slug = 'hori' and c.slug = 'controllere'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'CONTROLLER HORIPAD TURBO PENTRU NINTENDO SWITCH 2, NEGRU', 'controller-horipad-turbo-pentru-nintendo-switch-2-negru', 'CONTROLLER HORIPAD TURBO PENTRU NINTENDO SWITCH 2, NEGRU', 0, '{}'::jsonb
from brands b, categories c
where b.slug = 'hori' and c.slug = 'controllere'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'WIRELESS HORI HORIPAD (THE LEGEND OF ZELDA EDITION) PENTRU NINTENDO SWITCH/OLED', 'wireless-hori-horipad-the-legend-of-zelda-edition-pentru-nintendo-switch-oled', 'WIRELESS HORI HORIPAD (THE LEGEND OF ZELDA EDITION) PENTRU NINTENDO SWITCH/OLED', 0, '{}'::jsonb
from brands b, categories c
where b.slug = 'hori' and c.slug = 'controllere'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'CONTROLLER WIRELESS GULIKIT KK3 MAX, PC/NINTENDO SWITCH, ALB', 'controller-wireless-gulikit-kk3-max-pc-nintendo-switch-alb', 'CONTROLLER WIRELESS GULIKIT KK3 MAX, PC/NINTENDO SWITCH, ALB', 0, '{}'::jsonb
from brands b, categories c
where b.slug = 'gulikit' and c.slug = 'controllere'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'CONTROLLER HORI NOLVA MECHANICAL ALL-BUTTON ARCADE, PC/PS5', 'controller-hori-nolva-mechanical-all-button-arcade-pc-ps5', 'CONTROLLER HORI NOLVA MECHANICAL ALL-BUTTON ARCADE, PC/PS5', 0, '{}'::jsonb
from brands b, categories c
where b.slug = 'hori' and c.slug = 'controllere'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'HORI SPLIT PAD COMPACT EEVEE EVOLUTIONS PENTRU NINTENDO SWITCH SI NINTENDO SWITCH OLED', 'hori-split-pad-compact-eevee-evolutions-pentru-nintendo-switch-si-nintendo-switch-oled', 'HORI SPLIT PAD COMPACT EEVEE EVOLUTIONS PENTRU NINTENDO SWITCH SI NINTENDO SWITCH OLED', 0, '{}'::jsonb
from brands b, categories c
where b.slug = 'hori' and c.slug = 'controllere'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'CONTROLLER GULIKIT ES GRAY PENTRU PC, NINTENDO SWITCH', 'controller-gulikit-es-gray-pentru-pc-nintendo-switch', 'CONTROLLER GULIKIT ES GRAY PENTRU PC, NINTENDO SWITCH', 0, '{}'::jsonb
from brands b, categories c
where b.slug = 'gulikit' and c.slug = 'controllere'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'CONTROLLER GULIKIT ES PRO BLACK PENTRU PC, NINTENDO SWITCH', 'controller-gulikit-es-pro-black-pentru-pc-nintendo-switch', 'CONTROLLER GULIKIT ES PRO BLACK PENTRU PC, NINTENDO SWITCH', 0, '{}'::jsonb
from brands b, categories c
where b.slug = 'gulikit' and c.slug = 'controllere'
on conflict (slug) do nothing;

-- VOLAN GAMING (6 products)
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'VOLAN RACING WHEEL APEX PS5,PS4,PC', 'volan-racing-wheel-apex-ps5-ps4-pc', 'VOLAN RACING WHEEL APEX PS5,PS4,PC', 0, '{}'::jsonb
from brands b, categories c
where b.slug = 'hori' and c.slug = 'volan-gaming'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'VOLAN OVERDRIVE XBOX X/S,ONE,PC', 'volan-overdrive-xbox-x-s-one-pc', 'VOLAN OVERDRIVE XBOX X/S,ONE,PC', 0, '{}'::jsonb
from brands b, categories c
where b.slug = 'hori' and c.slug = 'volan-gaming'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'HORI MARIO KART RACING WHEEL PRO PENTRU NINTENDO SWITCH, SWITCH OLED SI PC', 'hori-mario-kart-racing-wheel-pro-pentru-nintendo-switch-switch-oled-si-pc', 'HORI MARIO KART RACING WHEEL PRO PENTRU NINTENDO SWITCH, SWITCH OLED SI PC', 0, '{}'::jsonb
from brands b, categories c
where b.slug = 'hori' and c.slug = 'volan-gaming'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'VOLAN GAMING HORI APEX SPF-022U (PS4, PS5, PC), NEGRU', 'volan-gaming-hori-apex-spf-022u-ps4-ps5-pc-negru', 'VOLAN GAMING HORI APEX SPF-022U (PS4, PS5, PC), NEGRU', 0, '{}'::jsonb
from brands b, categories c
where b.slug = 'hori' and c.slug = 'volan-gaming'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'HORI MARIO KART RACING WHEEL PRO DELUXE PENTRU NINTENDO SWITCH, SWITCH OLED SI PC', 'hori-mario-kart-racing-wheel-pro-deluxe-pentru-nintendo-switch-switch-oled-si-pc', 'HORI MARIO KART RACING WHEEL PRO DELUXE PENTRU NINTENDO SWITCH, SWITCH OLED SI PC', 0, '{}'::jsonb
from brands b, categories c
where b.slug = 'hori' and c.slug = 'volan-gaming'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'VOLAN HORI PRO DELUXE PENTRU NINTENDO SWITCH/PC', 'volan-hori-pro-deluxe-pentru-nintendo-switch-pc', 'VOLAN HORI PRO DELUXE PENTRU NINTENDO SWITCH/PC', 0, '{}'::jsonb
from brands b, categories c
where b.slug = 'hori' and c.slug = 'volan-gaming'
on conflict (slug) do nothing;

-- ACCESORII (13 products)
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Mousepad Varmilo Xl Deep Space, 90x40x3 cm', 'mousepad-varmilo-xl-deep-space-90x40x3-cm', 'Mousepad Varmilo Xl Deep Space, 90x40x3 cm', 0, '{}'::jsonb
from brands b, categories c
where b.slug = 'varmilo' and c.slug = 'accesorii'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Mousepad Varmilo Xl Monet, 90x40x3 cm', 'mousepad-varmilo-xl-monet-90x40x3-cm', 'Mousepad Varmilo Xl Monet, 90x40x3 cm', 0, '{}'::jsonb
from brands b, categories c
where b.slug = 'varmilo' and c.slug = 'accesorii'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Mousepad Varmilo Xl Mucha Biscuits, 90x40x3 cm', 'mousepad-varmilo-xl-mucha-biscuits-90x40x3-cm', 'Mousepad Varmilo Xl Mucha Biscuits, 90x40x3 cm', 0, '{}'::jsonb
from brands b, categories c
where b.slug = 'varmilo' and c.slug = 'accesorii'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'MOUSE PAD GAMING VARMILO HYGGE XL, MULTICOLOR', 'mouse-pad-gaming-varmilo-hygge-xl-multicolor', 'MOUSE PAD GAMING VARMILO HYGGE XL, MULTICOLOR', 0, '{}'::jsonb
from brands b, categories c
where b.slug = 'varmilo' and c.slug = 'accesorii'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'MOUSE PAD GAMING VARMILO AURORA XL, ALBASTRU', 'mouse-pad-gaming-varmilo-aurora-xl-albastru', 'MOUSE PAD GAMING VARMILO AURORA XL, ALBASTRU', 0, '{}'::jsonb
from brands b, categories c
where b.slug = 'varmilo' and c.slug = 'accesorii'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'MOUSE PAD GAMING VARMILO ASGARD XL, NEGRU', 'mouse-pad-gaming-varmilo-asgard-xl-negru', 'MOUSE PAD GAMING VARMILO ASGARD XL, NEGRU', 0, '{}'::jsonb
from brands b, categories c
where b.slug = 'varmilo' and c.slug = 'accesorii'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'FOLIE PROTECTIE HORI NSX-071E PENTRU NINTENDO SWITCH 2', 'folie-protectie-hori-nsx-071e-pentru-nintendo-switch-2', 'FOLIE PROTECTIE HORI NSX-071E PENTRU NINTENDO SWITCH 2', 0, '{}'::jsonb
from brands b, categories c
where b.slug = 'hori' and c.slug = 'accesorii'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'FOLIE PROTECTIE HORI ULTIMATE ANTI-GLARE PENTRU NINTENDO SWITCH 2', 'folie-protectie-hori-ultimate-anti-glare-pentru-nintendo-switch-2', 'FOLIE PROTECTIE HORI ULTIMATE ANTI-GLARE PENTRU NINTENDO SWITCH 2', 0, '{}'::jsonb
from brands b, categories c
where b.slug = 'hori' and c.slug = 'accesorii'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'FOLIE PROTECTIE HORI PREMIUM PENTRU NINTENDO SWITCH 2', 'folie-protectie-hori-premium-pentru-nintendo-switch-2', 'FOLIE PROTECTIE HORI PREMIUM PENTRU NINTENDO SWITCH 2', 0, '{}'::jsonb
from brands b, categories c
where b.slug = 'hori' and c.slug = 'accesorii'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'STAND DE INCARCARE HORI NSX-002E PENTRU NINTENDO SWITCH 2, NEGRU', 'stand-de-incarcare-hori-nsx-002e-pentru-nintendo-switch-2-negru', 'STAND DE INCARCARE HORI NSX-002E PENTRU NINTENDO SWITCH 2, NEGRU', 0, '{}'::jsonb
from brands b, categories c
where b.slug = 'hori' and c.slug = 'accesorii'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'HORI VAULT CASE (ANIMAL CROSSING) PENTRU NINTENDO SWITCH, SWITCH OLED SI SWITCH LITE', 'hori-vault-case-animal-crossing-pentru-nintendo-switch-switch-oled-si-switch-lite', 'HORI VAULT CASE (ANIMAL CROSSING) PENTRU NINTENDO SWITCH, SWITCH OLED SI SWITCH LITE', 0, '{}'::jsonb
from brands b, categories c
where b.slug = 'hori' and c.slug = 'accesorii'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Set Switch Akko Penguin Silentioase - 5 pin (45 Buc)', 'set-switch-akko-penguin-silentioase-5-pin-45-buc', 'Set Switch Akko Penguin Silentioase - 5 pin (45 Buc)', 0, '{}'::jsonb
from brands b, categories c
where b.slug = 'akko' and c.slug = 'accesorii'
on conflict (slug) do nothing;
insert into products (brand_id, category_id, name, slug, description, base_price, specs)
select b.id, c.id, 'Set Switch Akko Creamy Cyan Switch – Clicky - 5 pin (45 Buc)', 'set-switch-akko-creamy-cyan-switch-clicky-5-pin-45-buc', 'Set Switch Akko Creamy Cyan Switch – Clicky - 5 pin (45 Buc)', 0, '{}'::jsonb
from brands b, categories c
where b.slug = 'akko' and c.slug = 'accesorii'
on conflict (slug) do nothing;
